name: Trigger API Gateway on Push

on:
  push:
    branches:
      - github_actions

env:
  TENANT_ACCOUNT_ID: '940482412729'  # Replace with your account ID
  AWS_TENANT_REGION: 'ap-south-1'      # Replace with your region
  CLUSTER_NAME: 'test-fargate-cluster'     # Replace with your cluster name
  DesiredEKSVersion: '1.31'           # Replace with desired EKS version

jobs:
  trigger-api:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_TENANT_REGION }}

      - name: Trigger API Gateway
        run: |
          PAYLOAD=$(cat <<EOF
          {
            "Clusters": {
              "Upgrade": [
                {
                  "AccountId": "${TENANT_ACCOUNT_ID}",
                  "Region": "${AWS_TENANT_REGION}",
                  "ClusterName": "${CLUSTER_NAME}",
                  "UpgradeOptions": {
                    "DesiredEKSVersion": "${DesiredEKSVersion}"
                  }
                }
              ]
            }
          }
          EOF
          )
          
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            "${{ secrets.API_GATEWAY_ENDPOINT }}"
